public with sharing class Person {
    public Person() {

        /*
        @nonemum
    Name
    Age
    City

    setName(myName) {
        this.Name = myName
    }
    setAge()
    setCity()

    getName() {
        return this.Name;
    }
    getCity()
}

Person p1 = new Person()
p1.setName('Doe')

// p1.name = 'Ravi'

p1.getName()


new Person().setName('Himanshi').setAge(24)
5Aep8614S5Oxg.jnj.ASVuVuotEVilg80d4o.08yeIp7RK7hGiaFg7kCSfHC3qKbQwRW8gwPWJALzbeYYmpfwlF


JSON.serialize(p1)
{
    name: 'doe',
    city: 'BLR'
    age: 30
}


Class a = new Bar();


Left = Right
Right ko left me assign.
Dono ke type same ho, Typecasting

HTTPResponse respon = new HTTP().send(req)

HttpResponse res = ≈.send(req);
HttpResponse res = http.send(req);


Http http = new Http();
HttpResponse res = http.send(req);



req.setHeader('Kon Sa header', 'value')
req.setHeader('Authroization', 'Bearer randomToken')*/

    }
}